const SET_GAME = 'SET_GAME';
const SET_NAME = 'SET_NAME';
const SET_SOCKET_CUTOM_ID ='SET_SOCKET_CUTOM_ID';
const SET_SCORE = 'SET_SCORE';

export {
    SET_GAME,
    SET_NAME,
    SET_SOCKET_CUTOM_ID,
    SET_SCORE
}
