export const events = {
	DRAWING: 'drawing',
	CLEAR_CANVAS: 'clearCanvas',
	CREATE_ROOM: 'createRoom',
	JOIN_ROOM: 'joinRoom',
	PLAYER_JOIN: 'playerJoin',
	START_GAME: 'startGame',
	END_GAME: 'endGame',
	DISABLE_CANVAS: 'disableCanvas',
	START_TIMER: 'startTimer',
	MESSAGE: 'message',
	CORRECT_GUESS: 'correctGuess',
	CLOSE_GUESS: 'closeGuess',
	ROUND_COMPLETE: 'roundComplete',
	GET_PLAYERS: 'getPlayers',
	CHOOSING_WORD: 'choosing',
	CHOOSE_WORD: 'chooseWord',
	HIDE_WORD: 'hideWord',
	HINTS: 'hints',
	LAST_WORD: 'lastWord',
	UPDATE_SCORE: 'updateScore',
	CREATED_ROOM: 'roomCreated',
	GET_ROOMS: 'getRooms',
	SET_CUSTOM_CLIENT_ID: 'clientAfterConnection',
	GET_ROOM_PLAYERS: 'getPlayersInARoom',
	GET_SCORE: 'getScore'
}